Enhancement/13
yokohama/test_salon-1 pull request #15
Opened 2021-02-10 09:00 UTC by minty1202

お疲れ様です！お時間ある時に確認お願いいたします。
実装内容
product全般
categoryとの紐付け
category,productのdeleted_atカラムの追加

特にproduct :new :edit ではラジオボタンでcategory_idを取得できるようにしています。
問題なく動きますが、実装方法が間違っていましたら、ご指摘いただけると嬉しいです。

2021-02-10 22:36 UTC, minty1202 commented
セレクトボックスに変更いたしました。
ご確認お願いいたします

2021-02-11 11:19 UTC, yokohama requested changes

2021-02-11 11:19 UTC, yokohama commented on app/controllers/staffs/products_controller.rb
> +      @product = Product.find(params[:id])
同じメソッドが、edit,update,show,destroyに存在しています。before_actionでまとめる方法を考えてみてください

2021-02-11 11:19 UTC, yokohama commented on app/views/staffs/categories/show.html.erb
> +<% @products.each do |product| %>
@productsではなく、

@category.productsの方が無駄な変数代入がなくなります。

2021-02-11 11:56 UTC, minty1202 commented on app/controllers/staffs/products_controller.rb
> +      @product = Product.find(params[:id])
修正いたしました

2021-02-11 11:56 UTC, minty1202 commented on app/views/staffs/categories/show.html.erb
> +<% @products.each do |product| %>
修正いたしました

2021-02-11 11:56 UTC, minty1202 commented
コメント修正いたしました。
ご確認お願いいたします

2021-02-11 22:42 UTC, merged